### ISSUE TITLE
Possible duplicate of W3C Verifiable Credentials Data Model

### ISSUE THREAD

**Issue by codedust** [Governikus/IdentificationReport#1]
The [W3C Verifiable Credentials Data Model](https://www.w3.org/TR/vc-data-model/) seems to fulfill the same use case as the Identification Report Schema. Maybe the W3C VC Data Model could be used to fulfill the goal of an identification report.

**Comment by mrburnsDE** [comment]
Thanks for the link. The last time i looked at VC they were in a draft status. Will investigate this hint.
