### ISSUE TITLE
Versioning inside the Identification Report

### ISSUE THREAD

**Issue by JonasGroeger** [Governikus/IdentificationReport#2]
Hi!

I have two questions:

1. Will the IdentificationReport adhere to the [SemVer](semver.org/) standard?
2. Could we embed the schema version inside the example payload?

So this:

```diff
{
+   "$schema": "https://github.com/Governikus/IdentificationReport:1.0.1",
    "reportID": "be4f9806-0b5f-45c3-a008-96fd2750f8cb",
    "serverIdentity": "https://test.governikus-eid.de/gov_autent/async",
    "reportTime": "2020-06-25T10:20:39+02:00",
    "identificationDate": "2020-06-25T10:19:54+02:00",
    "idStatus": "success",
    "subjectRef":  {"firstName": "John","lastName": "Doe" },
    "contextInformation": ["Antrag auf Kindergeld: 0815/763763"],
    "idStatement": "successful identification sent by SAML-Assertion",
    "documentReferences":[{
      "documentName":"test.pdf",
      "hashAlgo":"SHA-256","digest":"0c2720631b927e25d5cb8b5ca2b9408c552ea76797e3419245931296732fd0d2"
  }],
    "loaSent": "http://eidas.europa.eu/LoA/low"
  }
```

The specific value of `$schema` is not that important as long as it somehow has the words `IdentificationReport` and the version in it.

We're using the IndentificationReport in [FIT-Connect](https://git.fitko.de/fit-connect/metadata-schema/-/issues/3) and require a stable version and self-identifying payload.

**Comment by mrburnsDE** [comment]
Hi,
thanks for your comment! We will comply to the semantic versioning. I pushed an updated readme and sample. Since this is only a change on documentation and sample i didn't release a new version. 

Regards
Hartje

**Comment by JonasGroeger** [comment]
@mrburnsDE You'll also need to add it to https://github.com/Governikus/IdentificationReport/blob/master/sample/sample-report.jws.

Also, what is this file for: https://github.com/Governikus/IdentificationReport/blob/master/sample/sample-report-jws-hints.txt ?

**Comment by mrburnsDE** [comment]
Thanks for your feedback again! I updated the JWS. I cannot remember why i pushed the hints file. Maybe i used it for debugging purposes. Also removed that one.

**Comment by JonasGroeger** [comment]
With pleasure
